### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by RPerrin13** [inquidia/PentahoSnowflakePlugin#6]
Hello, I'm using Windows 10 and Pentaho 6.1 Kettle (I've also tried w/ 7.0) and I get an error when trying to install this plugin via the Pentaho Marketplace (see attached).

![image](https://cloud.githubusercontent.com/assets/6909141/21967137/0c029986-db36-11e6-9b5c-21d9217caee7.png)

I already have the Snowflake jdbc driver installed.  Any thoughts?  

Richard Perrin
Rich@InfoScoutInc.com

**Comment by cdeptula** [comment]
This problem is almost definitely related to the Pentaho Marketplace and not the plugin itself.  I would guess you will get this error regardless of which plugin you try to install.  Some common reasons for this tend to be proxy or file permission issues.  Without the actual logs I cannot venture an accurate guess on what is causing this, nor am I the right person to help with marketplace issues.

That said, since it appears you are having problems with the marketplace I would recommend you manually install the plugin.  To do this all you have to do is unzip the below download to your data-integration/plugins folder and restart Pentaho.

https://github.com/inquidia/PentahoSnowflakePlugin/releases/download/1.1.0/snowflake-plugin-package-1.1.0.zip

**Comment by RPerrin13** [comment]
Yup, so the manual plugin installed worked like a charm.  I'm up and running w/ the Plugin.  Thanks so much for the follow up :)
